[package]
name = "redis-lua"
version = "0.1.0"
authors = ["YushiOMOTE <yushiomote@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0"
rmp-serde = "0.14"
redis-lua-macro = { path = "../redis-lua-macro" }
proc-macro-hack = "0.5"
redis = "0.13"
futures = "0.1"
